[package]
name = "vmf"
version = "0.0.0"
authors = ["quat <quat1024@users.noreply.github.com>"]
edition = "2018"

[dependencies]
serde = "1.0"
thiserror = "1.0"

[dev-dependencies.serde]
version = "1.0"
features = [ "derive" ]