[package]
name = "craft"
version = "0.0.0"
authors = ["quat <quat1024@users.noreply.github.com>"]
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["full"] }
tower = { version = "0.4", features = ["full"] }
async-trait = "0.1.50"